version: '2'
services:
  openfire:
    image: technomancer101/openfire:4.7.3
    ports:
      - "9090:9090/tcp"
      - "9091:9091/tcp"
      - "5222:5222/tcp"
      - "7443:7443/tcp"
    volumes:
      - /opt/openfire/data:/var/lib/openfire
      - /opt/openfire/logs:/var/log/openfire
